### ISSUE TITLE
Cannot.symlink

### ISSUE THREAD

**Issue by dlforrister** [stanstrup/convert.waters.raw#1]
experiencing this error. Any guidance?

Warning messages:
1: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_CHRO001.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_CHRO001.DAT', reason 'A required privilege is not held by the client'
2: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_CHRO002.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_CHRO001.DAT', reason 'A required privilege is not held by the client'
3: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_CHRO003.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_CHRO001.DAT', reason 'A required privilege is not held by the client'
4: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_CHRO004.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_CHRO001.DAT', reason 'A required privilege is not held by the client'
5: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_CHRO005.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_CHRO001.DAT', reason 'A required privilege is not held by the client'
6: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_CHRO006.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_CHRO001.DAT', reason 'A required privilege is not held by the client'
7: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_CHRO007.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_CHRO001.DAT', reason 'A required privilege is not held by the client'
8: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_CHRO008.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_CHRO001.DAT', reason 'A required privilege is not held by the client'
9: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_CHROMS.INF' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_CHROMS.INF', reason 'A required privilege is not held by the client'
10: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_extern.inf' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_extern.inf', reason 'A required privilege is not held by the client'
11: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC010.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC010.DAT', reason 'A required privilege is not held by the client'
12: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC010.IDX' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC010.IDX', reason 'A required privilege is not held by the client'
13: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC010.STS' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC010.STS', reason 'A required privilege is not held by the client'
14: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC011.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC011.DAT', reason 'A required privilege is not held by the client'
15: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC011.IDX' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC011.IDX', reason 'A required privilege is not held by the client'
16: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC011.STS' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC011.STS', reason 'A required privilege is not held by the client'
17: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC012.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC012.DAT', reason 'A required privilege is not held by the client'
18: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC012.IDX' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC012.IDX', reason 'A required privilege is not held by the client'
19: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC012.STS' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC012.STS', reason 'A required privilege is not held by the client'
20: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC013.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC013.DAT', reason 'A required privilege is not held by the client'
21: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC013.IDX' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC013.IDX', reason 'A required privilege is not held by the client'
22: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC013.STS' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC013.STS', reason 'A required privilege is not held by the client'
23: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC014.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC014.DAT', reason 'A required privilege is not held by the client'
24: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC014.IDX' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC014.IDX', reason 'A required privilege is not held by the client'
25: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC014.STS' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC014.STS', reason 'A required privilege is not held by the client'
26: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC015.DAT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC015.DAT', reason 'A required privilege is not held by the client'
27: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNC015.IDX' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNC015.IDX', reason 'A required privilege is not held by the client'
28: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_FUNCTNS.INF' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_FUNCTNS.INF', reason 'A required privilege is not held by the client'
29: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_HEADER.TXT' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_HEADER.TXT', reason 'A required privilege is not held by the client'
30: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_HISTORY.INF' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_HISTORY.INF', reason 'A required privilege is not held by the client'
31: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\\_INLET.INF' to 'K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw/_INLET.INF', reason 'A required privilege is not held by the client'
32: running command 'masswolf --mzXML "K:/XCMS_ANALYSIS/DDA_mzXML/temp.raw" "K:/XCMS_ANALYSIS/DDA_mzXML/IngU_MSMS_TEST_V1_func13.mzXML"' had status 65535

**Comment by stanstrup** [comment]
Is this a mounted network drive or something like that? It seems it cannot write a certain type if file that might be file system dependant.

**Comment by dlforrister** [comment]
Yes it is a mounted network drive. Same issue occurs when I copy to file to be converted to the local c drive. I also tried running R as an administrator. 

same warnings as before but with different directory.

1: In file.symlink(from = paste0(infiles[i], "/", to_copy),  ... :
  cannot symlink 'IngU_MSMS_TEST_V1.raw\' to 'C:/Users/Tom/Desktop/temp.raw/', reason 'Access is denied'
2: running command 'masswolf --mzXML "C:/Users/Tom/Desktop/temp.raw" "C:/Users/Tom/Desktop/IngU_MSMS_TEST_V1_func1.mzXML"' had status 65535

**Comment by stanstrup** [comment]
What version if R? http://r.789695.n4.nabble.com/Create-and-read-symbolic-links-in-Windows-td4666085.html seems there was a bug at some point. No idea if that is related.

Before we look for bugs can you check if you are able to make symlinks on windows?
Using a command prompt try something like:

```
mklink x:\PATH\IngU_MSMS_TEST_V1.raw\_INLET.INF' 'C:\Users\Tom\Desktop\_INLET.INF
```

Is your `infiles` full path? Not 100% sure if that is needed or not without checking but it could be.

**Comment by dlforrister** [comment]
Thank you for your prompt responses. 

I was unable to symlink using the example you have above. Though I think this could be due a mistake I made in setting the in file above. I say this  because by changing the infile to the full path I was able to process the samples and get past the previous permissions error.

However I'm a bit confused about how to set my experiments up so that the MSn spectra are convertible and readable for use with xcms2 and GNPS molecular networking platform. We have a waters instrument and we have an entire set of MS runs. We wold now like to target specific features for msms so we can find any potential hits in the databases (i.e. Massbank or metlin). I have created an msms expiriment with 12 peaks of interest. Waters qtof then creates a .Raw file with functions 1-15. function 1 = MS of entire experiment. function 2-13 are ms/ms of a specific mass and retention time. Function 14 = ms of Lue-Enk our lockmass and function 15 is PDA data. 

How would one then go about converting these? 
The options I am aware of are:

1) msconvert does not convert calibrated data.

2) convert.waters("K:/Thinkstation Files (UPLC-MS)/Current/2014_all_Inga_POS.PRO/Data/", "K:/converted") converts these to .mzdata which are readable into xcms but what I've read indicates parent mass information is lost, thus making it impossible to use for xcms2 and it is not supported by GNPS molecular networking.
3) Databride to CDF but same with mxdata parent mass info is lost. Also not accepted by GNPS

4) What appears to be the final option is: convert.waters2("C:/Users/Tom/Desktop/IngU_MSMS_TEST_V1.raw","C:/Users/Tom/Desktop",funcs=seq(1:14))

However rather than creating a single .mzXML file with many MSn which i think is what msconvert does. It produced 1 mxXML file for each function. Is that correct? 

This is what happened when I attempted to load this file into xcms using > xcmsRaw(filename = "IngU_MSMS_TEST_V1_func3.mzXML",includeMSn = T)
An "xcmsRaw" object with 20 mass spectra

Time range: 301.2-330.5 seconds (5-5.5 minutes)
Mass range: 33.5211-1984.3258 m/z
Intensity range: 17.7328-399 

MSn data on  0  mass(es)
	with  0  MSn spectra
Profile method: bin 
Profile step: 1 m/z (1951 grid points from 34 to 1984 m/z)

Memory usage: 0.311 MB
Warning message:
In mzR:::rampRawDataMSn(object@rampid) :
  MSn spectra requested but not found


Any help or guidance you can offer would be great! Sorry if this is not an appropriate place to pose this question as it seems you've fixed my original issue by using the full path, but I am a bit stuck and would appreciate the help.

Cheers,

Dale

**Comment by stanstrup** [comment]
I have opened a new issue for the MS2 problem.
